name: Deploy to Lightsail

permissions:
  contents: read
  packages: write      # GHCR 푸시를 위해 write 권한 필요 :contentReference[oaicite:15]{index=15}

on:
  push:
    branches: [ main ]

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_OWNER: quizup42
  IMAGE_NAME: quiz-platform
  DEPLOY_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # (1) 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # (2) AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # (3) GHCR(GitHub Container Registry) 로그인
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # 별도 PAT 사용 :contentReference[oaicite:16]{index=16}

      # (4) 이미지 빌드 & 푸시 (GHCR)
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.DEPLOY_TAG }}

      # (5) Compose 파일 서버 동기화
      - name: Sync Compose file to Lightsail
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/quizup/QuizUp_BE"
          overwrite: true

      # (5.1) 환경 변수 파일 서버 동기화
      - name: Sync .env.production to Lightsail
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          source: ".env.production"
          target: "/home/ubuntu/quizup/QuizUp_BE"
          overwrite: true

      # (6) SSH를 통한 Lightsail 배포 (key 옵션 사용)
      - name: Deploy via SSH to Lightsail
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}  # 시크릿에 저장된 개인 키 전체 텍스트 :contentReference[oaicite:17]{index=17}
          port: 22
          script: |
            # 프로젝트 디렉터리로 절대 경로로 이동
            cd /home/ubuntu/quizup/QuizUp_BE
            echo "Current directory: $(pwd)"
            ls -la

            # (2) GHCR 로그인
            echo "${{ secrets.GHCR_PAT }}" | docker login ${{ env.GHCR_REGISTRY }} -u ${{ github.actor }} --password-stdin

            # (3) Compose 파일을 명시하여 Pull & Up
            docker compose -f docker-compose.prod.yml --env-file .env.production pull
            docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build
